version: '3.8'

services:
  formtools:
    build: .
    container_name: formtools
    networks:
      - formtools_network
    ports:
      - 8080:80
    volumes:
      - ./formtools:/var/www/html:rw
    depends_on:
      - db
    restart: unless-stopped
  

  db:
    image: mariadb:10.5
    container_name: db
    networks:
      - formtools_network
    volumes:
      - formtools_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=formtools
      - MYSQL_USER=formtools
    restart: unless-stopped

networks:
  formtools_network:
  
volumes:
  formtools_db:
